/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIProcessingResult {
  'id' : string,
  'owner' : [] | [Principal],
  'metadata' : string,
  'processedAt' : Time,
  'resultType' : { 'imageCompression' : null } |
    { 'fileRecognition' : null },
  'processedFile' : [] | [ExternalBlob],
}
export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'id' : string,
  'blob' : ExternalBlob,
  'name' : string,
  'size' : bigint,
  'fileType' : string,
  'uploader' : Principal,
  'uploadTime' : Time,
}
export interface QRCodeSession {
  'creator' : Principal,
  'expiryTime' : Time,
  'creationTime' : Time,
  'fileId' : string,
  'isValid' : boolean,
}
export type Time = bigint;
export interface TransferRecord {
  'id' : string,
  'transferTime' : Time,
  'file' : FileMetadata,
  'sender' : Principal,
  'success' : boolean,
  'receiver' : Principal,
  'transferDuration' : bigint,
}
export interface UserProfile {
  'displayName' : string,
  'avatarUrl' : string,
  'online' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'compressImage' : ActorMethod<[string, ExternalBlob, bigint], ExternalBlob>,
  'createQRCodeSession' : ActorMethod<[string, bigint], string>,
  'fetchFileMetadataByQRCode' : ActorMethod<[string], [] | [FileMetadata]>,
  'getAIProcessingResult' : ActorMethod<[string], AIProcessingResult>,
  'getAllAIProcessingResults' : ActorMethod<[], Array<AIProcessingResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileMetadata' : ActorMethod<[string], FileMetadata>,
  'getOnlineUsers' : ActorMethod<[], Array<Principal>>,
  'getQRCodeSession' : ActorMethod<[string], QRCodeSession>,
  'getTransferHistory' : ActorMethod<[Principal], Array<TransferRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'invalidateQRCodeSession' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'recordAIProcessing' : ActorMethod<
    [
      string,
      { 'imageCompression' : null } |
        { 'fileRecognition' : null },
      string,
      [] | [ExternalBlob],
    ],
    undefined
  >,
  'recordTransfer' : ActorMethod<
    [string, Principal, Principal, FileMetadata, bigint, boolean],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOnlineStatus' : ActorMethod<[boolean], undefined>,
  'updateProfile' : ActorMethod<[string, string], undefined>,
  'uploadFile' : ActorMethod<
    [string, string, bigint, string, ExternalBlob],
    undefined
  >,
  'validateQRCodeSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];