/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const AIProcessingResult = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Opt(IDL.Principal),
  'metadata' : IDL.Text,
  'processedAt' : Time,
  'resultType' : IDL.Variant({
    'imageCompression' : IDL.Null,
    'fileRecognition' : IDL.Null,
  }),
  'processedFile' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'online' : IDL.Bool,
});
export const FileMetadata = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'size' : IDL.Nat,
  'fileType' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadTime' : Time,
});
export const TransferRecordData = IDL.Record({
  'id' : IDL.Text,
  'transferTime' : Time,
  'file' : FileMetadata,
  'sender' : IDL.Principal,
  'success' : IDL.Bool,
  'receiver' : IDL.Principal,
  'transferDuration' : IDL.Nat,
});
export const TransferRecord = IDL.Record({
  'id' : IDL.Text,
  'transferTime' : Time,
  'file' : FileMetadata,
  'sender' : IDL.Principal,
  'success' : IDL.Bool,
  'receiver' : IDL.Principal,
  'transferDuration' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'compressImage' : IDL.Func(
      [IDL.Text, ExternalBlob, IDL.Nat],
      [ExternalBlob],
      [],
    ),
  'getAIProcessingResult' : IDL.Func(
      [IDL.Text],
      [AIProcessingResult],
      ['query'],
    ),
  'getAllAIProcessingResults' : IDL.Func(
      [],
      [IDL.Vec(AIProcessingResult)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFileMetadata' : IDL.Func([IDL.Text], [FileMetadata], ['query']),
  'getOnlineUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getTransferHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(TransferRecordData)],
      ['query'],
    ),
  'getTransferRecord' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(TransferRecord)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'recordAIProcessing' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'imageCompression' : IDL.Null,
          'fileRecognition' : IDL.Null,
        }),
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
  'recordTransfer' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Principal, FileMetadata, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setOnlineStatus' : IDL.Func([IDL.Bool], [], []),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const AIProcessingResult = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Opt(IDL.Principal),
    'metadata' : IDL.Text,
    'processedAt' : Time,
    'resultType' : IDL.Variant({
      'imageCompression' : IDL.Null,
      'fileRecognition' : IDL.Null,
    }),
    'processedFile' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'online' : IDL.Bool,
  });
  const FileMetadata = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'size' : IDL.Nat,
    'fileType' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadTime' : Time,
  });
  const TransferRecordData = IDL.Record({
    'id' : IDL.Text,
    'transferTime' : Time,
    'file' : FileMetadata,
    'sender' : IDL.Principal,
    'success' : IDL.Bool,
    'receiver' : IDL.Principal,
    'transferDuration' : IDL.Nat,
  });
  const TransferRecord = IDL.Record({
    'id' : IDL.Text,
    'transferTime' : Time,
    'file' : FileMetadata,
    'sender' : IDL.Principal,
    'success' : IDL.Bool,
    'receiver' : IDL.Principal,
    'transferDuration' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'compressImage' : IDL.Func(
        [IDL.Text, ExternalBlob, IDL.Nat],
        [ExternalBlob],
        [],
      ),
    'getAIProcessingResult' : IDL.Func(
        [IDL.Text],
        [AIProcessingResult],
        ['query'],
      ),
    'getAllAIProcessingResults' : IDL.Func(
        [],
        [IDL.Vec(AIProcessingResult)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFileMetadata' : IDL.Func([IDL.Text], [FileMetadata], ['query']),
    'getOnlineUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getTransferHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(TransferRecordData)],
        ['query'],
      ),
    'getTransferRecord' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(TransferRecord)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'recordAIProcessing' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'imageCompression' : IDL.Null,
            'fileRecognition' : IDL.Null,
          }),
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
    'recordTransfer' : IDL.Func(
        [
          IDL.Text,
          IDL.Principal,
          IDL.Principal,
          FileMetadata,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setOnlineStatus' : IDL.Func([IDL.Bool], [], []),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, ExternalBlob],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };